### ISSUE TITLE
Input 'CHM' does not have square cells

### ISSUE THREAD

**Issue by Washburn1324** [AndyPL22/ForestTools#19]
Hey all, 

I'm having an issue defining tree tops with a CHM tiff I made. I attempt the ttops designation as described in the guide, but then it tells me
 "Error in vwf(CHM = k_plot_CHM, winFun = lin, minHeight = 2) : 
  Input 'CHM' does not have square cells"
I mildly understand the idea that it needs square cells, but how do I ensure the CHM has them / is there a way to convert to square cells to avoid this? 

Thanks,

Bryan

**Comment by andrew-plowright** [comment]
You can examine your CHM's information using `terra` or `raster`. For instance:

```
> terra::rast("my_chm.tif")
class       : SpatRaster 
dimensions  : 52036, 70612, 1  (nrow, ncol, nlyr)
resolution  : 0.25, 0.25  (x, y)
extent      : 480689, 498342, 5449526, 5462535  (xmin, xmax, ymin, ymax)
coord. ref. : NAD83 / UTM zone 10N (EPSG:26910) 
source      : my_chm.tif 
name        : my_chm 
```

Having non-rectangular cells is usually because your CHM is using a lat/lon reference system, which is typically inappropriate for fine-scale canopy analysis. Note that the `coord. ref` field above will tell you what your reference system is.

How did you get your CHM? If you have access to the underlying point cloud, I'd recommend re-generating it using a projected reference system. If not, you could resample it using `terra::resample`, but that wouldn't be ideal.

**Comment by Washburn1324** [comment]
Thanks for answering so promptly!
Using that method you mentioned I see this. 
> terra::rast(k_plot_CHM)
class       : SpatRaster 
dimensions  : 380, 408, 1  (nrow, ncol, nlyr)
resolution  : 0.1339687, 0.1340405  (x, y)
extent      : 511185.9, 511240.5, 5206483, 5206534  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=10 +datum=WGS84 +units=m +no_defs 
source      : Clip_CHM_K.tif 
name        :    Band_1 
min value   : -1.233101 
max value   : 35.976364 

I produced this CHM with drone imagery from a Mavic pro 2. Using drone2map I produced a DSM and DTM. Next pulled those into ArcGIS pro to subtract one from the other and get a CHM which I exported as tif. 

I found that when I tried pulling the DSM and DTM individually into R and subtract them it told me the resolutions were different which I am also not sure how to fix.

**Comment by andrew-plowright** [comment]
```
resolution : 0.1339687, 0.1340405 (x, y)
```

As you can see, the cells here are rectangular, which `ForestTools` doesn't like since it wants to create circular search windows and not oval ones.

Unfortunately I can't help you with drone2map since that's not software that I'm familiar with, but I suspect that is where your problem is. I'd suggest looking at drone2map's settings when generating the DSM and DTM. You should be able to define what resolution you want, such as 0.10 x 0.10 or 0.15 x 0.15. I'd also recommend ensuring that both the DSM and DTM have a similar extent and origin point so that they can be subtracted from each other.

**Comment by Washburn1324** [comment]
Your suggestion of specifying the x,y resolution was the ticket actually! I was able to export the file from ArcGIS pro with specified cell size so now it's square. Thanks!
