### ISSUE TITLE
Installing "ForestTools" package in R errors

### ISSUE THREAD

**Issue by fellicecity** [AndyPL22/ForestTools#27]
Hello, I've been trying to install the package for my current R version (4.10 (2021-05-18)).
But I receive an error of the package not being present in the current one. 
```
install.packages('ForestTools')

Installing package into ‘\\usc.internal/usc/studenthome/f_c024/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ForestTools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

So, I looked it up and saw another way to do it. The one with the devtools. But then I encountered another error again: 
```
devtools::install_github("andrew-plowright/ForestTools")

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘shiny’

```
Can you kindly help me on this? Thank you!

**Comment by andrew-plowright** [comment]
Hi @fellicecity, of course my first recommendation would be just to install the latest version of R, which is version 4.3.1. ForestTools requires version 4.2 at a minimum, so that should resolve the issue.

To be honest, I would have thought that the `install_github` route would throw a similar error. Unfortunately, I don't have an explanation for why the `shiny` package is being mentioned in that error message. It's definitely not in the `ForestTools` dependency tree. Maybe try to force its installation by running `install.packages("shiny")`?

**Comment by fellicecity** [comment]
Hello!

I asked my administrator to install the newest version of R and now the package has been installed.
Thank you, Andrew!
