### ISSUE TITLE
vwf quadruples tree top points

### ISSUE THREAD

**Issue by kylenessen** [AndyPL22/ForestTools#9]
When I run vwf, 1-4 points are generated on the pixel which is identified as the treetop. I have tried various permutations of the vwf arguments with no luck. Below is a screenshot of what I am talking about. 

![image](https://user-images.githubusercontent.com/37258183/60928575-d6750a00-a262-11e9-975b-098e217062a7.png)

Here is the code used to generate the points along with the CHM
```
lin <- function(x){x*0.4}
ttops <- vwf(CHM = area4, winFun = lin, maxWinDiameter = 99, minHeight = 3, minWinNeib = "rook")
plot(area4, xlab = "", ylab = "", xaxt='n', yaxt = 'n')
plot(ttops, col = "blue", pch = 20, cex = 0.5, add = TRUE)
ttops
```
[area4.zip](https://github.com/andrew-plowright/ForestTools/files/3375041/area4.zip)

Any idea of what's going on?

**Comment by andrew-plowright** [comment]
Hi Kyle. Apologies, I must have missed the notification for this issue.

The problem here is that it looks like this CHM was originally at a 1 m resolution, but was then resampled to a 0.5 m resolution. This created several 2 x 2 cell clusters with identical values.

The `raster` package has an easy way to return the CHM to its original resolution:
```
raster::aggregate(area4, fact=2)
```
That should fix the issue.

**Comment by kylenessen** [comment]
Thanks for getting back to me!

Not sure how why or how I resampled the CHM, but I can see how that would cause problems. I've tried vwf again on a different dataset and I'm getting clean results now.
